FROM almalinux:9
ARG project="naresh" \
    author="naresh"
RUN echo project=$project, author=$author
ENV project="naresh1" \
    author="naresh1"
RUN echo project=$project, author=$author    
CMD ["sleep", "100"]    